name: Run playwright tests
on:
  workflow_dispatch:
    inputs:
      testgroup:
        description: 'Test group to run'
        required: true
        default: 'API'
        type: choice
        options:
          - API
          - UI
  push:
    branches: [master]
jobs:
  containerised-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-noble
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run API tests only
        if: ${{ inputs.testgroup == 'API' || github.event_name == 'push' }}
        run: npm run api-tests
        env:
          HOME: /root
      - name: Run UI tests
        if: ${{ inputs.testgroup == 'UI' }}
        run: npm run ui-tests
        env:
          HOME: /root
      - name: Publish Test Summary Results
        if: always()
        run: npx github-actions-ctrf summary ctrf/ctrf-report.json
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
